# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-18 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='logo',
        ),
    ]
